CREATE TABLE HR.STUDENTS_MLV 
(
STUDENT_ID NUMBER,
DEPARTMENT_ID NUMBER,
TEACHER_ID NUMBER,
START_DATE DATE,
FULL_NAME VARCHAR2(100),
SCHOLARSHIP NUMBER);

 COMMENT ON COLUMN HR.STUDENTS_MLV.STUDENT_ID IS 'ИД студента';
 COMMENT ON COLUMN HR.STUDENTS_MLV.DEPARTMENT_ID IS 'ИД кафедры';
 COMMENT ON COLUMN HR.STUDENTS_MLV.TEACHER_ID IS 'ИД преподавателя';
 COMMENT ON COLUMN HR.STUDENTS_MLV.START_DATE IS 'Дата поступления';
 COMMENT ON COLUMN HR.STUDENTS_MLV.FULL_NAME IS 'ФИО студента';
 COMMENT ON COLUMN HR.STUDENTS_MLV.SCHOLARSHIP IS 'Стипендия студента';