SELECT ST.STUDENT_ID, 
       ST.DEPARTMENT_ID, 
       ST.TEACHER_ID, 
       ST.START_DATE, 
       ST.FULL_NAME, 
       ST.SCHOLARSHIP
FROM HR.STUDENTS_MLV ST
GROUP BY ST.STUDENT_ID,
       ST.DEPARTMENT_ID, 
       ST.TEACHER_ID, 
       ST.START_DATE, 
       ST.FULL_NAME, 
       ST.SCHOLARSHIP
HAVING COUNT(ST.STUDENT_ID) > 1
ORDER BY ST.STUDENT_ID;