SELECT ST.STUDENT_ID, 
       DP.DEPARTMENT_NAME, 
       ST.TEACHER_ID, 
       ST.START_DATE, 
       ST.FULL_NAME, 
       ST.SCHOLARSHIP
FROM HR.STUDENTS_MLV ST
INNER JOIN HR.DEPARTMENTS_MLV DP
ON ST.DEPARTMENT_ID = DP.DEPARTMENT_ID;