SELECT ST.STUDENT_ID,  
       ST.DEPARTMENT_ID, 
       ST.TEACHER_ID, 
       TO_CHAR (ST.START_DATE,'month') AS MONTH, 
       ST.FULL_NAME, 
       ST.SCHOLARSHIP
FROM HR.STUDENTS_MLV ST
WHERE ST.START_DATE BETWEEN TO_DATE('01.07.2019','dd.mm.yyyy')
AND TO_DATE ('31.07.2019','dd.mm.yyyy');